config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'quizrooms#index'

  resources :quizrooms, only: [ :show ] do
    resources :questions, only: [ :show ]
    resources :answers, only: [ :create ]
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :choice
  belongs_to :question
  belongs_to :quizroom
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/choice.rb
class Choice < ApplicationRecord
  belongs_to :question
  belongs_to :quizroom

  has_many :answers

  validates :option, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :quizroom
  belongs_to :user

  has_many :choices
  has_many :answers

  validates :utterance, :subject, presence: true
end

app/models/quizroom.rb
class Quizroom < ApplicationRecord
  has_many :questions
  has_many :choices
  has_many :answers

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers

  devise :database_authenticatable, :validatable, :rememberable

  validates :name, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    @answer = Answer.new(answer_params)
    @quizroom = find_quizroom
    @answer.question = @answer.choice.question
    @answer.quizroom = @quizroom
    @answer.user = current_user
    if @answer.save
      QuizroomChannel.broadcast_to(
        @quizroom,
        render_to_string(partial: "./questions/show_teacher/answer", locals: { answer: @answer })
      )
      redirect_to quizroom_path(@answer.quizroom)
    end
  end

  private

  def answer_params
    params.require(:answer).permit(:choice_id)
  end

  def find_quizroom
    Quizroom.find(params[:quizroom_id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.includes(:choice, :user)
    @answer = Answer.new
    @choice_array = set_choice_array
  end

  private

  def set_choice_array
    @question.choices.map do |choice|
      [choice.id, choice.option]
    end
  end
end

app/controllers/quizrooms_controller.rb
class QuizroomsController < ApplicationController
  def index
    @quizrooms = Quizroom.all
  end

  def show
    @quizroom = Quizroom.find(params[:id])
    if current_user.teacher
      @questions = set_questions
    else
      @questions = filter_done_questions(set_questions)
    end
  end

  private

  def set_questions
    Question.where(subject: @quizroom.name)
  end

  def filter_done_questions(questions)
    answers = Answer.where(user: current_user).includes(:question)
    questions_done = answers.map { |answer| answer.question }
    questions - questions_done
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FisHead</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag asset_path('fish.png') %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-lg-8">
          <div class="card-white my-4">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/questions/_teacher.html.erb
<div class="d-flex justify-content-end mb-2">
  <%= link_to '<i class="fas fa-undo-alt"></i><span>Voltar</span>'.html_safe, quizroom_path(question.quizroom), class:"back-btn" %>
</div>
<div class="question-header">
  <h1><%= question.utterance %></h1>
</div>
<h2>Respostas:</h2>
<div id="answers" data-quizroom-id="<%= question.quizroom.id %>">
  <% answers.each do |answer| %>
    <%= render 'questions/answer', answer: answer %>
  <% end %>
</div>

app/views/questions/show.html.erb
<% if current_user.teacher %>
  <%= render 'questions/show_teacher/teacher', question: @question, answers: @answers %>
<% else %>
  <%= render 'questions/show_student/student', question: @question, answer: @answer, choice_array: @choice_array %>
<% end %>

app/views/questions/show_shared/_question_header.html.erb
<div class="d-flex justify-content-end mb-2">
  <%= link_to '<i class="fas fa-undo-alt"></i><span>Voltar</span>'.html_safe, quizroom_path(question.quizroom), class:"back-btn" %>
</div>
<div class="question-header">
  <h1><%= question.utterance %></h1>
</div>

app/views/questions/show_student/_quizform.html.erb
<div class="quizform-container">
  <%= simple_form_for answer, url: quizroom_answers_path(question.quizroom) do |f| %>
    <%= f.collection_radio_buttons :choice_id, choice_array, :first, :last do |b| %>
      <div class="choice-item mb-2 py-2 px-3">
        <%= b.label { b.radio_button + " " + b.text } %>
      </div>
    <% end %>
    <div class="button-container mt-3">
      <%= f.button :submit, "Responder", class:"btn-quiz" %>
    </div>
  <% end %> 
</div>

app/views/questions/show_student/_student.html.erb
<%= render 'questions/show_shared/question_header', question: question %>
<div class="choice-container row justify-content-center mt-4 text-center">
  <div class="col-lg-8">
    <%= render 'questions/show_student/quizform', question: question, answer: answer, choice_array: choice_array %>
  </div>
</div>

app/views/questions/show_teacher/_answer.html.erb
<div class="row d-flex justify-content-center mt-4">
  <div class="col-lg-10">
    <%= render 'questions/show_teacher/answer_list', answer: answer %>
  </div>
</div>

app/views/questions/show_teacher/_answer_list.html.erb
<ul>
  <div class="answer-container" id="answer-<%= answer.id %>">
    <li class="animate__animated animate__fadeInDown">
      <div class="answer-item d-flex justify-content-between align-items-center mb-2 answer-<%= answer.choice.correct_option %>">
        <div class="answer-info">
          <h3>Nome: <%= answer.user.name %></h3>
          <p>Resposta: <%= answer.choice.option %></p>
        </div>
        <div class="answer-correction">
          <p><%= answer.choice.correct_option ? "Correta" : "Errada" %></p>
        </div>
      </div>
    </li>
  </div>
</ul>

app/views/questions/show_teacher/_teacher.html.erb
<%= render 'questions/show_shared/question_header', question: question %>
<h2>Respostas:</h2>
<div id="answers" data-quizroom-id="<%= question.quizroom.id %>">
  <% answers.each do |answer| %>
    <%= render 'questions/show_teacher/answer', answer: answer %>
  <% end %>
</div>

app/views/quizrooms/index.html.erb
<%= render 'quizrooms/index/header' %>
<h3>Assuntos disponíveis:</h3>
<%= render 'quizrooms/index/quizroom_list', quizrooms: @quizrooms %>

app/views/quizrooms/index/_header.html.erb
<div class="quizroom-header d-flex justify-content-between align-items-center mb-4">
  <div class="text-left">
    <h1 class="animate__animated animate__bounce">Olá, <%= current_user.teacher ? "Prof. #{current_user.name}" : current_user.name %>!</h1>
  </div>
  <div class="avatar">
    <%= image_tag current_user.url_pic %>
  </div>
</div>

app/views/quizrooms/index/_quizroom_list.html.erb
<div class="quizroom-list-wrapper row justify-content-center mt-5">
  <ul>
    <% quizrooms.each do |quizroom| %>
      <li class="animate__animated animate__fadeIn<%= quizroom.id.even? ? "Left" : "Right" %>">
        <%= link_to quizroom_path(quizroom), class: "quizroom-links" do %>
          <div class="d-flex align-items-center">
            <div class="hashtag mr-2">
              <i class="fab fa-slack-hash"></i>
            </div>
            <span><%= quizroom.name %></span>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/quizrooms/show.html.erb
<%= render 'quizrooms/show/header', quizroom: @quizroom %>
<h2>Questões:</h2>
<%= render 'quizrooms/show/question_list', quizroom: @quizroom, questions: @questions %>

app/views/quizrooms/show/_header.html.erb
<div class="d-flex align-items-top justify-content-between mb-2">
  <h1><i class="fab fa-slack-hash"></i> <%= quizroom.name %></h1>
  <%= link_to '<i class="fas fa-undo-alt"></i><span>Voltar</span>'.html_safe, root_path, class:"back-btn" %>
</div>

app/views/quizrooms/show/_question_list.html.erb
<div class="questions-list-wrapper row justify-content-center mt-4 text-center">
  <div class="col-lg-8">
    <ul>
      <% questions.each do |question| %>
        <li class="animate__animated animate__fadeIn<%= question.id.even? ? "Left" : "Right" %>">
          <%= link_to quizroom_question_path(quizroom, question), class:"question-links" do %>
            <div class="question-item mb-2 py-2 px-3">
              <span><%= question.utterance %></span>
            </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer mt-4">
<div class="container">
  <div class="links mt-3">
    <a href="#"><i class="fab fa-facebook-f"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fas fa-envelope"></i></a>
    <p>Essa web app foi desenvolvida com <i class="fas fa-coffee"></i> por<a href="https://github.com/pessanhadavi/fishead" id="signature" >David Pessanha</a>.</p>
  </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar py-2 mb-4">
  <%= link_to root_path, class: "navbar-logo" do %>
    <%= image_tag "fish.png" %>
  <% end %>

  <div class="nav-links">
    <ul>
      <% if user_signed_in? %>
        <div class="d-flex">
          <li class="nav-item">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= image_tag current_user.url_pic, class: "nav-avatar" %>
          </li>
        </div>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>